version: "3"
services: 
    app:
        container_name: docker_guide
        restart: always
        build: .
        ports:
            - "8080:8000" 
        links:
            - mongo
    
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - "27018-27017"
            
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - 'http.host=0.0.0.0'
            - 'transport.host=127.0.0.1'
            - 'ELASTIC_PASSWORD=changeme'
            - 'discovery.type=single-node'
        
        deploy:
            mode: replicated
            replicas: 1