version: "3"
services: 
    app:
        container_name: docker_guide
        restart: always
        build: .
        ports:
            - "8080:8000" 
        links:
            - mongo
    
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - "27018-27017"
            

// docker-compose build
// docker-compose up